name: gwells_locationqa
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - requests>=2.26
  - rasterio
  - geopandas>=0.10
  - jupyterlab>=3.2.1
  - pip
  - pip:
    - thefuzz==0.19.0
    - bcdata>=0.4.5
